server:
  port: 8081

test:
  message: "git push만으로 완벽하게 자동 업데이트 성공!"

# RabbitMQ 설정 (Spring Cloud Bus와 동일한 설정을 사용)
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest